// <auto-generated />
using System;
using Cine.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cine.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230507203303_avancemayo")]
    partial class avancemayo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cine.Shared.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CiudadId")
                        .HasColumnType("int");

                    b.Property<int>("ColombiaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("ColombiaId", "Name")
                        .IsUnique();

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Colombia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Colombia");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Funcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId", "Name")
                        .IsUnique();

                    b.ToTable("Funcion");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId", "Name")
                        .IsUnique();

                    b.ToTable("Pelicula");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Ciudad", b =>
                {
                    b.HasOne("Cine.Shared.Entities.Ciudad", null)
                        .WithMany("Ciudades")
                        .HasForeignKey("CiudadId");

                    b.HasOne("Cine.Shared.Entities.Colombia", "Colombia")
                        .WithMany("Ciudad")
                        .HasForeignKey("ColombiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colombia");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Funcion", b =>
                {
                    b.HasOne("Cine.Shared.Entities.Pelicula", "Pelicula")
                        .WithMany("Funciones")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Pelicula", b =>
                {
                    b.HasOne("Cine.Shared.Entities.Genero", "Genero")
                        .WithMany("Pelicula")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Ciudad", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Colombia", b =>
                {
                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Genero", b =>
                {
                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("Cine.Shared.Entities.Pelicula", b =>
                {
                    b.Navigation("Funciones");
                });
#pragma warning restore 612, 618
        }
    }
}
